### ISSUE TITLE
gym.error.NameNotFound: Environment `rtfm:groups_nl` doesn't exist. Did you mean: `groups_nl`?

### ISSUE THREAD

**Issue by yuejunpeng** [facebookresearch/RTFM#3]
I just downloaded the code, and used "pip install -e ." to set up RTFM. As a result, it succeeded.
However, when I want to try the model as follows: python play_gym.py -c --env groups_nl --shuffle_wiki
Traceback (most recent call last):
  File "play_gym.py", line 30, in <module>
    env = gym.make('rtfm:{}-v0'.format(args.env), featurizer=featurizer, partially_observable=args.partially_observable, room_shape=(args.height, args.width), shuffle_wiki=args.shuffle_wiki)
  File "/home/seg/miniconda3/envs/py38/lib/python3.8/site-packages/gym/envs/registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "/home/seg/miniconda3/envs/py38/lib/python3.8/site-packages/gym/envs/registration.py", line 490, in make
    versions = self.env_specs.versions(namespace, name)
  File "/home/seg/miniconda3/envs/py38/lib/python3.8/site-packages/gym/envs/registration.py", line 220, in versions
    self._assert_name_exists(namespace, name)
  File "/home/seg/miniconda3/envs/py38/lib/python3.8/site-packages/gym/envs/registration.py", line 297, in _assert_name_exists
    raise error.NameNotFound(message)
gym.error.NameNotFound: Environment `rtfm:groups_nl` doesn't exist. Did you mean: `groups_nl`?

How to debug?

**Comment by vzhong** [comment]
Yes sorry I think Gym made some backwards-incompatible changes. If you use the new version of gym, you can use the latter environment name.
